CREATE TABLE [dbo].[T_Employees_Login] (
    [ID]         BIGINT        IDENTITY (1, 1) NOT NULL,
    [CreatedDT]  DATETIME      NULL,
    [CreatedBY]  NVARCHAR (50) NULL,
    [ModifiedDT] DATETIME      NULL,
    [ModifiedBY] NVARCHAR (50) NULL,
    [IsActive]   TINYINT       NULL,
    [Year]       NVARCHAR (4)  NULL,
    [Month]      NVARCHAR (2)  NULL,
    [Username]   NVARCHAR (50) NULL,
    [DayIn1]     DATETIME      NULL,
    [DayOut1]    DATETIME      NULL,
    [DayIn2]     DATETIME      NULL,
    [DayOut2]    DATETIME      NULL,
    [DayIn3]     DATETIME      NULL,
    [DayOut3]    DATETIME      NULL,
    [DayIn4]     DATETIME      NULL,
    [DayOut4]    DATETIME      NULL,
    [DayIn5]     DATETIME      NULL,
    [DayOut5]    DATETIME      NULL,
    [DayIn6]     DATETIME      NULL,
    [DayOut6]    DATETIME      NULL,
    [DayIn7]     DATETIME      NULL,
    [DayOut7]    DATETIME      NULL,
    [DayIn8]     DATETIME      NULL,
    [DayOut8]    DATETIME      NULL,
    [DayIn9]     DATETIME      NULL,
    [DayOut9]    DATETIME      NULL,
    [DayIn10]    DATETIME      NULL,
    [DayOut10]   DATETIME      NULL,
    [DayIn11]    DATETIME      NULL,
    [DayOut11]   DATETIME      NULL,
    [DayIn12]    DATETIME      NULL,
    [DayOut12]   DATETIME      NULL,
    [DayIn13]    DATETIME      NULL,
    [DayOut13]   DATETIME      NULL,
    [DayIn14]    DATETIME      NULL,
    [DayOut14]   DATETIME      NULL,
    [DayIn15]    DATETIME      NULL,
    [DayOut15]   DATETIME      NULL,
    [DayIn16]    DATETIME      NULL,
    [DayOut16]   DATETIME      NULL,
    [DayIn17]    DATETIME      NULL,
    [DayOut17]   DATETIME      NULL,
    [DayIn18]    DATETIME      NULL,
    [DayOut18]   DATETIME      NULL,
    [DayIn19]    DATETIME      NULL,
    [DayOut19]   DATETIME      NULL,
    [DayIn20]    DATETIME      NULL,
    [DayOut20]   DATETIME      NULL,
    [DayIn21]    DATETIME      NULL,
    [DayOut21]   DATETIME      NULL,
    [DayIn22]    DATETIME      NULL,
    [DayOut22]   DATETIME      NULL,
    [DayIn23]    DATETIME      NULL,
    [DayOut23]   DATETIME      NULL,
    [DayIn24]    DATETIME      NULL,
    [DayOut24]   DATETIME      NULL,
    [DayIn25]    DATETIME      NULL,
    [DayOut25]   DATETIME      NULL,
    [DayIn26]    DATETIME      NULL,
    [DayOut26]   DATETIME      NULL,
    [DayIn27]    DATETIME      NULL,
    [DayOut27]   DATETIME      NULL,
    [DayIn28]    DATETIME      NULL,
    [DayOut28]   DATETIME      NULL,
    [DayIn29]    DATETIME      NULL,
    [DayOut29]   DATETIME      NULL,
    [DayIn30]    DATETIME      NULL,
    [DayOut30]   DATETIME      NULL,
    [DayIn31]    DATETIME      NULL,
    [DayOut31]   DATETIME      NULL,
    CONSTRAINT [PK_T_Employees_Login] PRIMARY KEY CLUSTERED ([ID] ASC)
);

