CREATE TABLE [dbo].[T_Employees] (
    [ID]                     BIGINT         IDENTITY (1, 1) NOT NULL,
    [CreatedDT]              DATETIME       NULL,
    [CreatedBY]              NVARCHAR (50)  NULL,
    [ModifiedDT]             DATETIME       NULL,
    [ModifiedBY]             NVARCHAR (50)  NULL,
    [IsActive]               TINYINT        NULL,
    [Username]               NVARCHAR (50)  NULL,
    [Password]               NVARCHAR (50)  NULL,
    [FirstName]              NVARCHAR (50)  NULL,
    [MiddleName]             NVARCHAR (50)  NULL,
    [LastName]               NVARCHAR (50)  NULL,
    [DateOfBirth]            DATETIME       NULL,
    [PersonalEMail]          NVARCHAR (50)  NULL,
    [PersonalNumber]         NVARCHAR (50)  NULL,
    [CorrespondanceAddress1] NVARCHAR (100) NULL,
    [CorrespondanceAddress2] NVARCHAR (100) NULL,
    [CorrespondanceCity]     NVARCHAR (50)  NULL,
    [CorrespondanceState]    NVARCHAR (50)  NULL,
    [CorrespondanceCountry]  NVARCHAR (50)  NULL,
    [CorrespondanceEMail]    NVARCHAR (50)  NULL,
    [CorrespondanceNumber]   NVARCHAR (50)  NULL,
    [PermanentAddress1]      NVARCHAR (100) NULL,
    [PermanentAddress2]      NVARCHAR (100) NULL,
    [PermanentCity]          NVARCHAR (50)  NULL,
    [PermanentState]         NVARCHAR (50)  NULL,
    [PermanentCountry]       NVARCHAR (50)  NULL,
    [PermanentEMail]         NVARCHAR (50)  NULL,
    [PermanentNumber]        NVARCHAR (50)  NULL,
    [EmergencyNumber]        NVARCHAR (50)  NULL,
    [JoiningDate]            DATETIME       NULL,
    [ReleaseDate]            DATETIME       NULL,
    [ImageFileName]          NVARCHAR (100) NULL,
    [EmployeeID]             NVARCHAR (50)  NULL,
    [Gender]                 NVARCHAR (10)  NULL,
    [BankName]               NVARCHAR (50)  NULL,
    [Branch]                 NVARCHAR (50)  NULL,
    [AccountNumber]          NVARCHAR (50)  NULL,
    [IFSC_Code]              NVARCHAR (50)  NULL,
    [IsCorrespondance]       TINYINT        NULL,
    [IsRoleAssign]           TINYINT        NULL,
    [MaritalStatus]          NVARCHAR (30)  NULL,
    [CompanyEmail]           NVARCHAR (200) NULL,
    [OfficeCenter_Core]      NVARCHAR (100) NULL,
    [EmployeeType_Core]      NVARCHAR (100) NULL,
    [DateOfMarriage]         DATETIME       NULL,
    CONSTRAINT [PK_T_Employees] PRIMARY KEY CLUSTERED ([ID] ASC)
);

