CREATE TABLE [dbo].[T_Opportunities] (
    [ID]                         BIGINT          IDENTITY (1, 1) NOT NULL,
    [CreatedDT]                  DATETIME        NULL,
    [CreatedBY]                  NVARCHAR (50)   NULL,
    [ModifiedDT]                 DATETIME        NULL,
    [ModifiedBY]                 NVARCHAR (50)   NULL,
    [IsActive]                   TINYINT         NULL,
    [OpportunityNumber]          NVARCHAR (50)   NULL,
    [OpportunityName]            NVARCHAR (500)  NULL,
    [ProjectDomain_Core]         NVARCHAR (50)   NULL,
    [ProjectExpectedStartDate]   DATETIME        NULL,
    [ProjectExpectedEndDate]     DATETIME        NULL,
    [OpportunityStatus_Core]     NVARCHAR (50)   NULL,
    [ProjectExpectedAmount]      NVARCHAR (50)   NULL,
    [ProjectDomainType_Core]     NVARCHAR (50)   NULL,
    [ProjectLanguage_Core]       NVARCHAR (50)   NULL,
    [EmployeeID]                 NVARCHAR (50)   NULL,
    [OpportunityCreatedDT]       DATETIME        NULL,
    [AccountID]                  NVARCHAR (50)   NULL,
    [Description]                NVARCHAR (4000) NULL,
    [ContactID]                  NVARCHAR (50)   NULL,
    [ReferenceContactID]         NVARCHAR (50)   NULL,
    [ReferencePercentage]        NVARCHAR (10)   NULL,
    [ProjectDomainCategory_Core] NVARCHAR (100)  NULL,
    [Priority]                   NVARCHAR (1)    NULL,
    [ProjectRemainingAmount]     NVARCHAR (50)   NULL,
    [ReceiptCreatedDate]         DATETIME        NULL,
    [ProjectStatus_Core]         NVARCHAR (50)   NULL,
    [ProjectCreatedDT]           DATETIME        NULL,
    CONSTRAINT [PK_T_Opportunities] PRIMARY KEY CLUSTERED ([ID] ASC)
);

