CREATE TABLE [dbo].[T_Timesheets] (
    [ID]                BIGINT          IDENTITY (1, 1) NOT NULL,
    [CreatedDT]         DATETIME        NULL,
    [CreatedBY]         NVARCHAR (50)   NULL,
    [ModifiedDT]        DATETIME        NULL,
    [ModifiedBY]        NVARCHAR (50)   NULL,
    [IsActive]          TINYINT         NULL,
    [EmployeeID]        NVARCHAR (50)   NULL,
    [Year]              NVARCHAR (5)    NULL,
    [Month]             NVARCHAR (5)    NULL,
    [Week]              NVARCHAR (5)    NULL,
    [OpportunityNumber] NVARCHAR (50)   NULL,
    [ProjectTask_ID]    BIGINT          NULL,
    [Description]       NVARCHAR (1000) NULL,
    [Day1]              NVARCHAR (5)    NULL,
    [Day2]              NVARCHAR (5)    NULL,
    [Day3]              NVARCHAR (5)    NULL,
    [Day4]              NVARCHAR (5)    NULL,
    [Day5]              NVARCHAR (5)    NULL,
    [Day6]              NVARCHAR (5)    NULL,
    [Day7]              NVARCHAR (5)    NULL,
    [TotalHours]        NVARCHAR (10)   NULL,
    [IsSubmit]          TINYINT         NULL,
    [ApprovedDT]        DATETIME        NULL,
    [ApprovedBy]        NVARCHAR (50)   NULL,
    [ApprovedMessage]   NVARCHAR (1000) NULL,
    [RejectedDT]        DATETIME        NULL,
    [RejectedBy]        NVARCHAR (50)   NULL,
    [RejectedMessage]   NVARCHAR (1000) NULL,
    CONSTRAINT [PK_T_Timesheets] PRIMARY KEY CLUSTERED ([ID] ASC)
);

